site_name: Data Science OSSU
site_url: https://NandesLima.github.io/data-science/
site_description: Um caminho open-source para educação autodidata em Ciência de Dados.
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.expand
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

extra_css:
  - stylesheets/custom.css
  - stylesheets/global-modern.css

nav:
  - 'Início': index.md
  - 'Currículo':
      - '01. Introdução à Data Science': 01-introducao.md
      - '02. Programação (Python)': 02-programacao.md
      - '03. Matemática (Cálculo e Álgebra)': 03-matematica.md
      - '04. Estatística e Probabilidade': 04-estatistica.md
      - '05. Bancos de Dados (SQL)': 05-banco-de-dados.md
      - '06. Machine Learning': 06-machine-learning.md
      - '07. Projeto Final': 07-projeto-final.md
  - 'Sobre': README.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - tables
